### ISSUE TITLE
Add Feature: Meme Steganography Support

### ISSUE THREAD

**Issue by digitalcraft** [GoatseSeal/GoatseCoin#1]
Instead of sending coins wallet addresses, one could retrieve the wallet address from data encoded within dank memes.

This is a sick idea. put me down for 1% ICO.

**Comment by GoatseSeal** [comment]
Thanks man, we'll put you down for $10 million of the $1 billion ICO. You can get 1,000 coins free for sending a 0 Eth transaction to 0x72855c26ee72bbe2db66a9a50eae750bd0f5bc88 though (with 100k gas) and we'll be launching the dapp tonight to be used from the GoatseCoinMemes subreddit.

After launching on our subreddit we're going to create our own site specifically for Goatse Coin memes that'll simplify the process of using the coin and the dapp so this suggestion could be a great fit there.
